src/lxqtplatformtheme.cpp
src/lxqtplatformtheme.h

Before:
After:
Looking reeeally nicer now. Credits for [qt5ct](http://sourceforge.net/projects/qt5ct/)'s and [KDE](http://quickgit.kde.org/?p=frameworkintegration.git&a=tree&h=9f7123484e71a5db35d3560aa904fb95f56a40d3&hb=2d53a53c22b1bd392238d76f16e57596c965fc9e&f=src%2Fplatformtheme)'s developers.
Fixes lxde/lxqt#695.

Refactor our Qt plugin to make use of the original colors from Qt widget styles

---

CMakeLists.txt
src/CMakeLists.txt
src/lxqtplatformtheme.h
src/lxqtsystemtrayicon.cpp
src/lxqtsystemtrayicon.h
src/statusnotifieritem/dbustypes.cpp
src/statusnotifieritem/dbustypes.h
src/statusnotifieritem/org.kde.StatusNotifierItem.xml
src/statusnotifieritem/statusnotifieritem.cpp
src/statusnotifieritem/statusnotifieritem.h

This is a work in progress. Besides a few `TODO` notes left in the source code, we still need to make the apps listen to the StatusNotifierWatcher in case the panel restarts.
Fixes lxde/lxqt#817.

Support the StatusNotifierItem spec natively

---

src/lxqtplatformtheme.h

Keep support for the good old `QSystemTrayIcon`. Inspiration from [here](https://bugreports.qt.io/browse/QTBUG-35658?focusedCommentId=272798&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-272798).
Discussion in lxde/lxqt-panel#241.

SNI: don't create a SNI if support isn't available

---

AUTHORS
Digia-Qt-LGPL-Exception-version-1.1

there is nothing licensed with GPL2
added Digia-Qt-LGPL-Exception-version-1.1 license file
fixes lxde/lxqt/issues/804

Removed GPL2, added Digia Qt LGPL Exception version 1.1

---

src/lxqtplatformtheme.cpp

This half of the solution of https://github.com/lxde/lxqt/issues/1010
After it gets in, we can stop adding `XDG_DATA_HOME` to `XDG_DATA_DIRS` in lxqt-common.

Xdg icon theme paths

---

CMakeLists.txt
src/CMakeLists.txt

Drop liblxqt build and runtime dependency. It's actually not needed.

Use the new lxqt-build-tools package

---

src/statusnotifieritem/statusnotifieritem.cpp
src/statusnotifieritem/statusnotifieritem.h

StatusNotifierItems were cloned, because only one object was registered
for all StatusNotifierItem services.
Adding support for multiple notifiers fixes https://github.com/lxde/lxqt/issues/1105 for me.

Fix multiple StatusNotifierItems.

---

src/lxqtplatformtheme.cpp
src/lxqtplatformtheme.h

1. avoid leak by creating new object
2. we don't support overriding of colors -> default Qt palette is OK

LXQtPlatformTheme: Do not provide own palette

---

src/statusnotifieritem/statusnotifieritem.cpp

The solution with Qt>=5.7 is to use the qAsConst() macro.
But the qAsConst macro is just a const_cast to const T&.

Prevent a possible C++11 range for detach

---

src/lxqtplatformtheme.cpp
src/lxqtplatformtheme.h

Fixes forcing the Fusion palette even if other style engine used (as
the QPlatformTheme::palette() does force the fusion).
The mentioned regression was introduced by d5f8558ee6ad.
fixes lxde/lxqt#1312

LXQtPlatformTheme: Make Qt use default palette

---

src/lxqtplatformtheme.cpp

Fixes https://github.com/lxde/lxqt/issues/1341.
QML apps may not have qApp. So, we shouldn't use our dialog with them; otherwise, they would crash.

Handle QML (as @PCMan suggested)

---

src/lxqtfiledialoghelper.cpp

Won't build if variable is not declared (Ot < 5.9.0).

Fix missing variable declaration

---

src/statusnotifieritem/statusnotifieritem.cpp

Seems that they are not needed.

Remove unused parameter from onServiceOwnerChanged

---

src/lxqtplatformtheme.cpp

Fixes https://github.com/lxde/lxqt/issues/1426.
ShowShortcutsInContextMenus is false by default and, contrary to it name, it isn't just about context menus.

Handle the new hint ShowShortcutsInContextMenus

---

src/CMakeLists.txt
src/lxqtplatformtheme.cpp

Replaced with the ranged-for loop.
Using QT_NO_FOREACH to enforce it.

Drop Qt foreach.

---

src/CMakeLists.txt
src/lxqtplatformtheme.cpp
src/lxqtsystemtrayicon.cpp
src/statusnotifieritem/statusnotifieritem.cpp

* Disables automatic conversions from 8-bit strings (char *) to unicode
QStrings.
* Disables automatic conversion from QString to 8-bit strings (char *).
* Disables automatic conversions from QByteArray to const char * or const
void *.
* Disables automatic conversions from QString (or char *) to QUrl.
* Use QStringBuilder for more efficient string creation.
It make us aware of string and encoding conversions.

Don't use automatic string conversions

---

CMakeLists.txt
src/CMakeLists.txt
src/lxqtplatformtheme.cpp

Alternative approch to @luis-pereira, introduce a option - if ON (default) be strict about the usage of fm-qt, no fallbacks and no magic allowed.

Make fm-qt a build dependency

---

src/lxqtplatformtheme.cpp
src/lxqtplatformtheme.h

Only the window (= button) color can be configured for now — `QPalette::QPalette(const QColor&)` calculates the other colors automatically — but, if needed, more customization could be added later, although, IMHO, it is better not to confuse users with too many colors.
The default color is that of Fusion's window.
If an option is added to `lxqt-config`, users could change not only Fusion's look-and-feel but also Breeze's, without needing KDE's systemsettings5.
Note 1: This was started to compensate for the ugly color Qt 5.15 gave to Fusion. IMO, that's a Qt issue but we don't need to worry about it.
Note 2: I'll make another PR for `lxqt-config` after the current one is decided.
Closes https://github.com/lxqt/lxqt-qtplugin/issues/54

Made the palette configurable in `LXQtPlatformTheme`

---

src/lxqtplatformtheme.cpp
src/lxqtplatformtheme.h

Three mistakes are corrected in the previous commit (https://github.com/lxqt/lxqt-qtplugin/commit/8a5a1999762c4c020e1cf3939d6eb6acf84b9a71), the first one being a serious bug. The fixes are as follows:
1. `LXQtPlatformTheme::loadSettings()` may be called multiple times due to changes in `~/.config/lxqt/lxqt.conf`. Therefore, `LXQtPalette_` should be deleted before being created again; otherwise, a memory leak will exist.
2. The new key `window_color` should belong to the "Qt" group because it is about a Qt setting.
3. If the value of `window_color` is changed, the application should be restyled; otherwise, the color change won't have effect immediately and the application should be restarted to reflect it.

Fixed mistakes in setting window color

---

src/lxqtplatformtheme.cpp

Generally, resetting a widget's palette from outside its code is a bad practice because the palette may have been changed for a reason.
If the custom palette of a widget needs an update when the style changes, the program itself is responsible for that; otherwise, the program has a bug — as in libfm-qt's places view (which I'll fix soon) and Dolphin's main view (which will never be fixed).

Do not reset widget palettes on changing style

---

src/lxqtplatformtheme.cpp

Because Qt's default highlight color is `#000080` while that of Fusion is `#3c8ce6`. Not only the latter is more elegant but also the patch fixes the color change after restarting apps.
Also, the highlighted text color is set to white for the sake of certainty.

Enforce Fusion's highlight color when setting window color

---

src/lxqtplatformtheme.cpp
src/lxqtplatformtheme.h

Eight palette colors are supported.
Also:
1. Colors are moved to a separate section named "Palette".
2. The app is polished after its palette is set. Previously, the lack of polishing interfered with styles that had internal palettes (like Kvantum and gtk2), so that an app restart was needed for them to show their own colors.
An `lxqt-config` PR will follow this to use it.

Support more palette colors for better customization

---

src/statusnotifieritem/statusnotifieritem.cpp

id is passed by value and only copied once.

Moving parameter to avoid unnecessary copies

---

src/lxqtplatformtheme.cpp

Qt implicitly assumes that the base and window colors don't have a high contrast with each other and uses the latter to get some colors related to the former, resulting in unreadable texts:
1. Qt sets the disabled base color to the window color. The current patch leaves the disabled base color to be equal to the enabled one (disabled widgets are distinguished from enabled ones in other ways) because the window color may have a high contrast with it and make disabled texts unreadable.
2. Qt gets the alternate base color (used by some item views) by mixing the base and window colors. The patch gets it by decreasing/increasing the lightness of the base color a little.
Closes https://github.com/lxqt/lxqt-qtplugin/issues/69
NOTE: If window and base colors have a high contrast with each other, …

Workaround for Qt's poor handling of some dark palettes

---

src/lxqtplatformtheme.cpp
src/lxqtplatformtheme.h

`MouseCursorTheme` and `MouseCursorSize` were introduced into Qt 6.5.
Closes https://github.com/lxqt/lxqt-qtplugin/issues/78

Set mouse cursor theme and size

---

src/lxqtplatformtheme.cpp
src/lxqtplatformtheme.h

The default is 0, which means that the Qt style sets it. Any value less than 16 is seen as 0, and values greater than 48 are seen as 48.
Closes https://github.com/lxqt/lxqt-qtplugin/issues/90

Set toolbar icon size

---

CMakeLists.txt
src/CMakeLists.txt

The 'Qt6FooPrivate' targets have been split into separate CMake files
in Qt 6.9, and require a 'find_package(Qt6FooPrivate)' call starting
with Qt 6.10.
See also: https://bugreports.qt.io/browse/QTBUG-87776

cmake: fix build with Qt 6.10
